/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    DCol: typeof import('vue-devui/grid/index.es.js')['Col']
    DDataGrid: typeof import('vue-devui/data-grid/index.es.js')['DataGrid']
    DForm: typeof import('vue-devui/form/index.es.js')['Form']
    DFormItem: typeof import('vue-devui/form/index.es.js')['FormItem']
    DInput: typeof import('vue-devui/input/index.es.js')['Input']
    DModal: typeof import('vue-devui/modal/index.es.js')['Modal']
    DRadio: typeof import('vue-devui/radio/index.es.js')['Radio']
    DRadioGroup: typeof import('vue-devui/radio/index.es.js')['RadioGroup']
    DRow: typeof import('vue-devui/grid/index.es.js')['Row']
    DSplitter: typeof import('vue-devui/splitter/index.es.js')['Splitter']
    DSplitterPane: typeof import('vue-devui/splitter/index.es.js')['SplitterPane']
    DTextarea: typeof import('vue-devui/textarea/index.es.js')['Textarea']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('vue-devui/loading/index.es.js')['LoadingDirective']
  }
}
